name: Deploy Static Site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' if that's your default branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Upload static site
        uses: actions/upload-pages-artifact@v3.0.1  # ✅ use v3.0.1, not just v2 or v3
        with:
          path: .  # or './docs' if files are in the docs folder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
